# Generated by Django 4.1.7 on 2023-04-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='soft_delete',
            field=models.BooleanField(default=False, verbose_name='soft_delete'),
        ),
        migrations.AddField(
            model_name='product',
            name='soft_delete',
            field=models.BooleanField(default=False, verbose_name='soft_delete'),
        ),
        migrations.AddField(
            model_name='review',
            name='soft_delete',
            field=models.BooleanField(default=False, verbose_name='soft_delete'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='review'),
        ),
    ]
